### PR TITLE
feat: use alert styles when possible

### LINKED ISSUE #19: Links in info admonitions are indistinguishable
Hello, I’ve found that `info` admonitions that have links are indistinguishable. Here’s an example:
image

### PR DESCRIPTION
**Pull request by elviswolcott**
resolves #19
infma_update

### CODE REVIEW

**Comment by elviswolcott** [comment]
@phoqe does this look better? still not amazing contrast, but it is using the styles from infima now

**Comment by phoqe** [comment]
Hmm, @elviswolcott I don't see the `info` container anywhere? Or is that the alias for `important`? In Docusaurus 2, that box is a bit darker, as you can see [here](https://docs.rmuif.com/docs/scripts).

**Comment by elviswolcott** [comment]
Yes, `info` and `important` are aliased. I updated the styles and classes in dev tools to match what this PR would produce and it looks like this
docs rmuif com_docs_scripts_

**Comment by elviswolcott** [comment]
As I said, not great contrast but it's using Infima fully now.

**Comment by phoqe** [comment]
Alright, that works. Thank you @elviswolcott for the update!

**Comment by elviswolcott** [comment]
v1.2.0 is out with this fix.

**Pull request merged**
